name: 'Terraform Validate'

on:
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read    # This is required for actions/checkout

jobs:
  validate:
    name: 'Terraform Validate'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Initialize a new or existing Terraform working directory (without backend)
    - name: Terraform Init
      run: terraform init -backend=false

    # Validates the configuration files in a directory
    - name: Terraform Validate
      run: terraform validate
